#Connection Pool, javax.mail
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      username: ENC(OaDgZ2H8FZr1mqzA3dd8uA==)
      password: ENC(tfVUj0d52KmQacrfhs7DWQ==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(CcHq2DJpsB3b+OfuzeU2ZcK22itm0oT1AI0tnxW6XSc=)
    password: ENC(KjqUYNZ4JhPfkGiLgeMQXmUikvv5OnOAGN1kIDzpTQw=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  main:
#    web-application-type: none  #Do not use embeded tomcat
 
# mybyties
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml
#  type-aliases-package: com.gdu.myhome.dto
  
# charater encoding, session, port
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
  port: 8080
  
# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor